//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressConfigurationSpec) DeepCopyInto(out *EgressConfigurationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressConfigurationSpec.
func (in *EgressConfigurationSpec) DeepCopy() *EgressConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(EgressConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkCheckConfigurationSpec) DeepCopyInto(out *NetworkCheckConfigurationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkCheckConfigurationSpec.
func (in *NetworkCheckConfigurationSpec) DeepCopy() *NetworkCheckConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkCheckConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfServiceNamespace) DeepCopyInto(out *SelfServiceNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfServiceNamespace.
func (in *SelfServiceNamespace) DeepCopy() *SelfServiceNamespace {
	if in == nil {
		return nil
	}
	out := new(SelfServiceNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SelfServiceNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfServiceNamespaceList) DeepCopyInto(out *SelfServiceNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SelfServiceNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfServiceNamespaceList.
func (in *SelfServiceNamespaceList) DeepCopy() *SelfServiceNamespaceList {
	if in == nil {
		return nil
	}
	out := new(SelfServiceNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SelfServiceNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfServiceNamespaceSpec) DeepCopyInto(out *SelfServiceNamespaceSpec) {
	*out = *in
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AdditionalAnnotations != nil {
		in, out := &in.AdditionalAnnotations, &out.AdditionalAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EgressConfigurations != nil {
		in, out := &in.EgressConfigurations, &out.EgressConfigurations
		*out = make([]EgressConfigurationSpec, len(*in))
		copy(*out, *in)
	}
	if in.NetworkChecks != nil {
		in, out := &in.NetworkChecks, &out.NetworkChecks
		*out = make([]NetworkCheckConfigurationSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfServiceNamespaceSpec.
func (in *SelfServiceNamespaceSpec) DeepCopy() *SelfServiceNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(SelfServiceNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfServiceNamespaceStatus) DeepCopyInto(out *SelfServiceNamespaceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfServiceNamespaceStatus.
func (in *SelfServiceNamespaceStatus) DeepCopy() *SelfServiceNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(SelfServiceNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}
